sudo: false
language: python
python:
  - "2.7"
before_install:
  - wget https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.35.zip -nv
  - unzip -q google_appengine_1.9.35.zip
  - openssl aes-256-cbc -K $encrypted_e43729c6d3d1_key -iv $encrypted_e43729c6d3d1_iv -in client_secret.json.enc -out client_secret.json -d
install:
  - pip install -r requirements.txt -t lib
script:
  - nosetests
before_deploy:
  - rm -rf google_appengine_1.9.35.zip google_appengine
deploy:
  provider: gae
  skip_cleanup: true
  version: prod
  keyfile: client_secret.json
  project: xye-bot
  default: true
