sudo: false
language: go
go:
  - tip
before_install:
  - wget https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.36.zip -nv
  - unzip -q google_appengine_1.9.36.zip
  - openssl aes-256-cbc -K $encrypted_e43729c6d3d1_key -iv $encrypted_e43729c6d3d1_iv -in client_secret.json.enc -out client_secret.json -d
before_deploy:
  - rm -rf google_appengine_1.9.36.zip google_appengine .git
deploy:
  provider: gae
  skip_cleanup: true
  version: go
  keyfile: client_secret.json
  project: xye-bot
  default: false
